project:
  type: book

  output-dir: ./docs

book:
  title: "Data exploration toolkit for cultural data"
  author: "Stefano Rapisarda & Barbara Romero Ferron (RDM, UU)"
  date: last-modified
  search: true
  chapters:
    - index.qmd
    - parts/supplements/schedule.qmd
    - part: "Preparation"
      chapters:
      - parts/preliminaries/set_up.qmd
    - part: "Data Workflow"
      chapters:
      - parts/data_analysis/organising_your_data.qmd
      - parts/data_analysis/ch1_reading_data.ipynb
      - parts/data_analysis/ch2_exploring_data.ipynb
      - parts/data_analysis/ch3_data_cleaning.ipynb
      - parts/data_analysis/ch4_data_analysis.ipynb
    - parts/supplements/summary.qmd
    - parts/supplements/what-next.qmd
    - parts/supplements/glossaries.qmd
    - parts/supplements/resources.qmd
  repo-url: https://CentreForDigitalHumanities.github.io/det_cultural_data
  sidebar:
    logo: course_logo.png
bibliography: parts/supplements/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
  epub:
    cover-image: cover.png