# Resources {.unnumbered}

## Research Support

- Utrecht University Library [website](https://www.uu.nl/en/university-library)

- Centre for Digital Humanities (CDH) [website](https://cdh.uu.nl/)

## Datasets

- **SlaveVoyages**: collaborative digital initiative that compiles and makes publicly accessible records of the largest slave trades in history. [link](https://www.slavevoyages.org/)

- **Cooper Hewitt collection**: over 30 Centuries of design online, from ancient Roman marble to Pre-Columbian texttiles, Renaissance drawings, contermporary 3D-printed chars, and digital code. [link](https://github.com/cooperhewitt/collection)
  
- **KU Libraries Special Collections**: portraits dataset of descriptive metadata representing all the single-file documents with graphic art from the Special Collections of the KU Leuven Libraries that depict people. [link](https://github.com/KU-Leuven-Libraries/Portraits-Collection-Dataset)
  
- **The Magister Dixit Collection (Leuven)**: 552 manuscripts of lecture notes of the Old University of Leuven (1425-1797). [link](https://github.com/KULeuvenDigitalisering/Magister-Dixit-Collection-Dataset)
  
- **Getty-Knoedler Stock Books**: more than 40,000 records transcribed from the 11 painting stock books  and enhanced with information from the 21 paintings and watercolors sales books of M. Knoedler & Co. in New York (1872-1970). [link](https://github.com/thegetty/provenance-index-csv/blob/main/knoedler/README.md)
  
- **Pantheon Project: Historical Popularity Index**: The Pantheon 1.0 data measures the global popularity of historical characters according to the metrics of their Wikidata pages in different languages. [link](https://www.kaggle.com/datasets/mit/pantheon-project)

- **National Gallery of Art Open Data**: some of the National Gallery of Art (Washington D. C.) database made public for exploration and educational purposes. [link](https://github.com/NationalGalleryOfArt/opendata)

## Programming

- Python [webpage](https://www.python.org/);

- Pandas (Python Data Analysis package) [webpage](https://pandas.pydata.org/);

- Matplotlib (Python visualization package) [webpage](https://matplotlib.org/);

- Seaborn webpage (Python visualization package) [webpage](https://seaborn.pydata.org/).